CREATE SCHEMA IF NOT EXISTS project1;

CREATE TABLE IF NOT EXISTS book_table (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name varchar(100) NOT NULL,
      author varchar(100) NOT NULL,
      isbn varchar(100) NOT NULL
);